version: '3.1'
services:
  itoken-zipkin:
    restart: always
    image: 192.168.141.178:5000/itoken-zipkin
    container_name: itoken-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network

networks:
  zipkin_network: