spring:
  application:
    name: itoken-zipkin   # 指定本服务的名称；

server:
  port: 9411     # 指定本服务开启的端口号；


management:    # Spring Boot Admin 服务端配置；
  metrics:   # 2.8版本不需要这段配置，2.10之后才有；
    web:
      server:
        auto-time-requests: false