spring:
  application:
    name: itoken-eureka   # 指定本服务的名称；
  boot:
    admin:                # Spring Boot Admin 服务监控；
      client:
        url: http://localhost:8084   # 指定Admin服务端的地址+端口，本服务作为Admin的客户端被其监控；
  zipkin:
    base-url: http://localhost:9411  # 配置 Zipkin Server 的地址；

server:
  port: 8761              # 指定本服务开启的端口号；

eureka:
  instance:
    hostname: localhost        # 指定eureka服务器的地址
  client:
    registerWithEureka: false  # 指定该项目作为eureka服务端存在
    fetchRegistry: false       # 不设置为false表示该项目是客户端；
    serviceUrl:                # 指定Eureka服务端地址，根据此地址注册将本服务到Eureka服务端；
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:               # Spring Boot Admin 服务端配置；
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info   # 若写成*，则显示的信息项更多；