spring:
  application:
    name: itoken-zuul   # 指定本服务的名称；

server:
  port: 8769   # 指定本服务开启的端口号；

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: itoken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: itoken-web-posts