spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://192.168.141.180:8084
  zipkin:
    base-url: http://192.168.141.180:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:  # 配置哨兵的地址
      master: mymaster   # 服务器中sentinel.conf中配置的名字
      nodes: 192.168.141.180:26380,192.168.141.180:26381,192.168.141.180:26382

server:
  port: 8502

eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.141.180:8761/eureka/,http://192.168.141.180:8861/eureka/,http://192.168.141.180:8961/eureka/
      defaultZone: http://192.168.141.180:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
