spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://192.168.141.180:8084
  zipkin:
    base-url: http://192.168.141.180:9411
  # 配置数据源
  datasource:
    druid:
      url: jdbc:mysql://192.168.141.180:3307/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501              # 指定本服务开启的端口号；

mybatis:
  # 实体类的存放路径
  type-aliases-package: com.zxj.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.zxj.itoken.service.admin.mapper: debug

eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.141.180:8761/eureka/,http://192.168.141.180:8861/eureka/,http://192.168.141.180:8961/eureka/
       defaultZone: http://192.168.141.180:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
