spring:
  application:
    name: itoken-service-admin

  # 配置数据源
  datasource:
    druid:
      url: jdbc:mysql://192.168.141.180:3307/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501              # 指定本服务开启的端口号；

