# 未验证
version: '3.1'
services:
  itoken-service-redis:
    restart: always
    image: 192.168.75.128:5000/itoken-service-redis
    container_name: itoken-service-redis
    ports:
      - 8502:8502
    networks:
      - service_redis_network

networks:
  service_redis_network: