version: '3.1'

services:
  itoken-eureka:
    restart: always
    image: 192.168.141.178:5000/itoken-eureka
    container_name: itoken-eureka
    ports:
      - 8761:8761
    networks:
      - eureka_network
networks:
  eureka_network:

#services:
#  itoken-eureka-1:
#    restart: always
#    image: 192.168.141.178:5000/itoken-eureka
#    container_name: itoken-eureka-1
#    ports:
#      - 8761:8761
#    networks:
#      - eureka_network_1
#
#  itoken-eureka-2:
#    restart: always
#    image: 192.168.141.178:5000/itoken-eureka
#    container_name: itoken-eureka-2
#    ports:
#      - 8861:8761
#    networks:
#      - eureka_network_2
#
#  itoken-eureka-3:
#    restart: always
#    image: 192.168.141.178:5000/itoken-eureka
#    container_name: itoken-eureka-3
#    ports:
#      - 8961:8761
#    networks:
#      - eureka_network_3
#
#networks:
#  eureka_network_1:
#  eureka_network_2:
#  eureka_network_3: