stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    - /usr/local/maven/apache-maven-3.6.1/bin/mvn clean package
    - cp target/itoken-zuul-1.0.0-SNAPSHOT.jar docker
    - cd docker
    - cp /usr/local/docker/dockerize-linux-amd64-v0.6.1.tar.gz .
    - docker build -t 192.168.141.178:5000/itoken-zuul .

push:
  stage: push
  script:
    - docker push 192.168.141.178:5000/itoken-zuul

run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)



